[package]
name = "server01"
version = "0.1.0"
edition = "2021"

[dependencies]
hecs = "0.9.1"
ctrlc = "3.2.3"
anyhow = "1.0.66"
log = "0.4.17"
fern = "0.6.1"
chrono = "0.4.23"

shared = { path = "../shared" }